/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/******************************************************************************
 * @project-02    STM32 <-> ESP32-P4 SPI Communication (Master → Slave Bring-up)
 *
 * @purpose
 * This project demonstrates a practical SPI communication setup where:
 *
 *   - STM32F407VGT6 acts as SPI Master
 *   - ESP32-P4 acts as SPI Slave
 *   - Data is transmitted from STM32 to ESP32 over MOSI
 *   - ESP32 receives and prints data via UART for validation
 *
 * The primary goal is to establish a reliable SPI communication link
 * between two different MCU platforms.
 *
 * ----------------------------------------------------------------------------
 * @current_scope
 * This firmware currently implements:
 *
 *   - STM32 configured as SPI Master (SPI2)
 *   - Manual GPIO-based Chip Select (CS) control (PB12)
 *   - Fixed-length frame transmission (64 bytes)
 *   - Blocking SPI transmit API (polling-based)
 *   - Periodic transmission of ASCII payload
 *
 * ESP32-P4 receives:
 *   - SPI data using SPI slave driver
 *   - Prints received data over UART for debugging
 *
 * ----------------------------------------------------------------------------
 * @hardware_mapping
 * STM32 (Master - SPI2):
 *   PB12 -> Manual Chip Select (CS)
 *   PB13 -> SPI2_SCLK
 *   PB15 -> SPI2_MOSI
 *   PB14 -> SPI2_MISO (currently unused)
 *
 * ESP32-P4 (Slave):
 *   GPIO21 -> CS
 *   GPIO6  -> SCLK
 *   GPIO4  -> MOSI (Slave RX)
 *   GPIO5  -> MISO (Slave TX, optional)
 *
 * Common:
 *   GND ↔ GND (mandatory)
 *
 * ----------------------------------------------------------------------------
 * @spi_configuration
 * STM32 SPI Configuration:
 *
 *   - Peripheral      : SPI2
 *   - Mode            : Master
 *   - Direction       : Full duplex (TX only used currently)
 *   - Data Size       : 8-bit
 *   - Clock Polarity  : CPOL = 0
 *   - Clock Phase     : CPHA = 0
 *   - SPI Mode        : Mode 0
 *   - NSS Management  : Software (SSM enabled, SSI set)
 *   - Chip Select     : Manual GPIO (PB12)
 *
 * Baud Rate:
 *   SPI_CLK_DIV2 (high speed)
 *   NOTE: For bring-up/debug, slower clocks (DIV16/DIV64) are recommended.
 *
 * ----------------------------------------------------------------------------
 * @communication_protocol
 * Current protocol is intentionally simple:
 *
 *   - Fixed frame size: 64 bytes
 *   - First N bytes contain ASCII payload
 *   - Remaining bytes are zero-padded
 *
 * Example payload:
 *   "SPI Communication from STM32F407VGT6 DISCOVERY Board!"
 *
 * Transmission sequence:
 *   1. CS LOW
 *   2. Send 64-byte frame
 *   3. Wait for BSY = 0
 *   4. CS HIGH
 *
 * ----------------------------------------------------------------------------
 * @why_manual_cs_is_used
 * Instead of hardware NSS, manual CS (GPIO) is used because:
 *
 *   - Provides explicit transaction control
 *   - Matches real-world SPI slave expectations
 *   - Easier debugging on logic analyzer
 *   - Works reliably across different MCU vendors
 *
 * ----------------------------------------------------------------------------
 * @driver_behavior_expectations
 * The SPI driver (spi_send_data) is expected to:
 *
 *   - Wait for TXE before writing each byte
 *   - Write data using 8-bit access
 *   - Wait for BSY to clear before returning
 *
 * Important:
 *   TXE = Data register empty
 *   BSY = Actual transmission finished on wire
 *
 * ----------------------------------------------------------------------------
 * @debugging_notes
 * During development, the following issues were encountered:
 *
 *   1. DMA alignment errors on ESP32 slave side
 *   2. Incorrect GPIO mapping
 *   3. SPI clock too fast during initial bring-up
 *   4. Loose / unreliable jumper connections
 *
 * Key lesson:
 *   Hardware issues (wiring/contacts) can mimic protocol failures.
 *
 * ----------------------------------------------------------------------------
 * @known_limitations
 *
 *   - No SPI receive handling on STM32
 *   - No dynamic packet length handling
 *   - No CRC/error detection
 *   - Blocking SPI only (no DMA/interrupts)
 *   - No retry/timeout logic
 *
 * ----------------------------------------------------------------------------
 * @recommended_next_steps
 *
 *   Step 1:
 *     Replace ASCII payload with known test patterns:
 *       0x55, 0xAA, 0x12, 0x34
 *
 *   Step 2:
 *     Enable MISO and test full-duplex communication
 *
 *   Step 3:
 *     Implement length + payload protocol
 *
 *   Step 4:
 *     Add CRC/checksum validation
 *
 *   Step 5:
 *     Move to DMA-based SPI for performance
 *
 * ----------------------------------------------------------------------------
 * @summary
 * This project successfully demonstrates:
 *
 *   - Cross-platform SPI communication (STM32 ↔ ESP32)
 *   - Proper CS-framed transactions
 *   - Reliable data transfer over MOSI
 *
 * If incorrect data is observed:
 *
 *   Check in order:
 *     1. Wiring correctness
 *     2. Common ground
 *     3. SPI mode (CPOL/CPHA)
 *     4. Clock speed
 *     5. Signal integrity
 *
 ******************************************************************************/
#include <stdint.h>
#include "main.h"
#include <string.h>

void SystemInit(void)
{
#if (__FPU_PRESENT == 1U) && (__FPU_USED == 1U)
    SCB->CPACR |= ((3UL << (10U * 2U)) | (3UL << (11U * 2U)));
    __DSB();
    __ISB();
#endif
}

void delay_nop(uint32_t count)
{
    while (count--)
    {
        __asm volatile ("nop");
    }
}

/******************************************************************************
 * @brief      Handles unrecoverable application errors.
 *
 * @details    Disables interrupts and traps the CPU in an infinite loop,
 *             allowing the debugger to halt execution and inspect the system
 *             state at the point of failure.
 *
 * @return     None
 ******************************************************************************/
void Error_Handler(void)
{
    __disable_irq();

    while (1)
    {
        __NOP();
    }
}

volatile float dbg_adc_raw = 2048.0f;
volatile float dbg_vref = 3.3f;
volatile float dbg_adc_voltage = 0.0f;
volatile float dbg_sensor_offset = 1.65f;
volatile float dbg_sensor_sensitivity = 0.330f;
volatile float dbg_sensor_value = 0.0f;
volatile float dbg_filtered_value = 0.0f;
volatile uint32_t dbg_fpu_counter = 0;

SPI_Handle_t spi2_t;
GPIO_Handle_t spi_gpio_t;

static void FPU_DebugCalc(void);
void spi2_gpio_init(GPIO_Handle_t *spi_gpio_t);
void spi2_periph_init(SPI_Handle_t *spi2_t);

int main(void)
{
    const char user_data[] = "SPI Communication from STM32F407VGT6 DISCOVERY Board!";
    uint8_t tx_frame[64] = {0};

    spi2_gpio_init(&spi_gpio_t);
    spi2_periph_init(&spi2_t);

    memcpy(tx_frame, user_data, strlen(user_data));

    while (1)
    {
        gpio_set_pin_level(GPIOB, GPIO_PIN_12, 0);   // CS low

        spi_send_data(SPI2, tx_frame, sizeof(tx_frame));

        while (SPI2->SR & (1U << SPI_SR_BSY)); // Wait till entire buffer is sent over SPI MOSI Line
        gpio_set_pin_level(GPIOB, GPIO_PIN_12, 1);   // CS high

        // FPU_DebugCalc();
        delay_nop(5000000);
    }
}

static void FPU_DebugCalc(void)
{
    dbg_adc_voltage = (dbg_adc_raw * dbg_vref) / 4095.0f;
    dbg_sensor_value = (dbg_adc_voltage - dbg_sensor_offset) / dbg_sensor_sensitivity;
    dbg_filtered_value = (0.90f * dbg_filtered_value) + (0.10f * dbg_sensor_value);

    dbg_adc_raw += 17.0f;
    if (dbg_adc_raw > 4095.0f)
    {
        dbg_adc_raw = 0.0f;
    }

    dbg_fpu_counter++;
}

void spi2_gpio_init(GPIO_Handle_t *spi_gpio_t)
{
	spi_gpio_t->pGPIOx_addr = GPIOB;
	spi_gpio_t->pin_config.Mode = GPIO_MODE_ALTFN;
	spi_gpio_t->pin_config.Alternate = GPIO_AF5_SPI2;
	spi_gpio_t->pin_config.OPType = GPIO_OP_PP;
	spi_gpio_t->pin_config.Pull = GPIO_NOPULL;
	spi_gpio_t->pin_config.Speed = GPIO_SPEED_FREQ_HIGH;

	spi_gpio_t->pin_config.Pin = GPIO_PIN_13; // Config of SCLK-PB13
	gpio_init(spi_gpio_t);

	spi_gpio_t->pin_config.Pin = GPIO_PIN_15; // Config of MOSI-PB15
	gpio_init(spi_gpio_t);

//	spi_gpio_t->pin_config.Pin = GPIO_PIN_14; // Config of MISO-PB14
//	gpio_init(spi_gpio_t);

	// PB12 as manual CS GPIO, not AF
	spi_gpio_t->pin_config.Mode = GPIO_MODE_OUTPUT;
	spi_gpio_t->pin_config.Alternate = 0;
	spi_gpio_t->pin_config.Pin = GPIO_PIN_12; // Config of NSS-PB12
	gpio_init(spi_gpio_t);

    gpio_set_pin_level(GPIOB, GPIO_PIN_12, 1); // CS idle high
}

void spi2_periph_init(SPI_Handle_t *spi2_t)
{
	spi2_t->Instance = SPI2;
	spi2_t->Init.Direction = SPI_COM_FD;
	spi2_t->Init.Mode = SPI_MODE_MASTER;
	spi2_t->Init.BaudRatePrescaler = SPI_CLK_DIV2; // 8MHz sclk
	spi2_t->Init.DataSize = BYTE_FRAME_LEN; // 8Bit mode
	spi2_t->Init.CLKPhase = SPI_CPHA_LOW;
	spi2_t->Init.CLKPolarity = SPI_CPOL_LOW;
	spi2_t->Init.NSS = SPI_SSM_ENABLED;

	spi_init(spi2_t); // This sets the settings while spi2 is disabled
	spi_ssi_state(spi2_t->Instance, ENABLE);
    spi_set_state(spi2_t->Instance, ENABLE);
}
