/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/******************************************************************************
 * @project-01    STM32 SPI2 Master Transmit Learning / Bring-up Example
 *
 * @purpose
 * This project is a simple SPI master-transmit reference for STM32,
 * intended for:
 *   1. learning SPI basics,
 *   2. verifying GPIO alternate-function SPI pin configuration,
 *   3. confirming MOSI/SCLK waveform generation on a logic analyzer,
 *   4. serving as a clean starting point before integrating a real SPI slave.
 *
 * ----------------------------------------------------------------------------
 * @current_scope
 * This firmware currently uses STM32 as:
 *   - SPI Master
 *   - Transmit-only for practical testing
 *   - No external slave connected during initial validation
 *
 * The present validation method is:
 *   - send ASCII string "HelloWorld" repeatedly on MOSI
 *   - observe SCLK + MOSI on logic analyzer
 *   - verify correct byte stream and clock timing
 *
 * ----------------------------------------------------------------------------
 * @hardware_mapping
 * SPI2 pin mapping used in this example:
 *   PB13 -> SPI2_SCLK
 *   PB15 -> SPI2_MOSI
 *
 * Optional / not currently used in this test:
 *   PB14 -> SPI2_MISO
 *   PB12 -> SPI2_NSS
 *
 * Notes:
 * - For logic-analyzer-only testing, only SCLK, MOSI, and common GND are needed.
 * - MISO is not required until a real slave is connected.
 * - NSS/CS is also not strictly required for waveform observation, but it becomes
 *   important for real slave communication and for clean analyzer transaction framing.
 *
 * ----------------------------------------------------------------------------
 * @spi_configuration
 * Current SPI2 settings:
 *   - Peripheral      : SPI2
 *   - Role            : Master
 *   - Direction       : Full duplex configuration
 *   - Frame size      : 8-bit
 *   - Clock polarity  : CPOL = 0
 *   - Clock phase     : CPHA = 0
 *   - Mode            : SPI Mode 0
 *   - NSS management  : Software slave management (SSM enabled, SSI set)
 *   - Bit order       : MSB first
 *
 * Baud rate:
 *   BaudRatePrescaler is currently set to SPI_CLK_DIV4.
 *   Actual SPI clock depends on the SPI2 input clock from the MCU clock tree.
 *   Always verify real SCLK on logic analyzer rather than trusting comments alone.
 *
 * ----------------------------------------------------------------------------
 * @why_this_project_exists
 * This project was created to validate the custom SPI driver and understand
 * practical SPI behavior before moving to real slave-device communication.
 *
 * Main things proven using this project:
 *   - GPIO AF configuration for SPI2 works
 *   - SPI peripheral initialization works
 *   - blocking transmit API works
 *   - repeated MOSI transmission is correct
 *   - observed decode issues were mostly analyzer/framing/capture related,
 *     not fundamental SPI driver failure
 *
 * ----------------------------------------------------------------------------
 * @important_logic_analyzer_notes
 * During bring-up, several confusing decoder issues were observed.
 * These are important for future debugging:
 *
 * 1. No CS/NSS line means poor analyzer framing
 *    ------------------------------------------------
 *    When no chip-select/enable signal is provided to the analyzer, the
 *    analyzer may decode some bursts incorrectly, especially first/last bytes
 *    or separated burst groups.
 *
 *    This does NOT necessarily mean STM32 transmitted wrong data.
 *    Often it is just decoder boundary guessing.
 *
 * 2. Single short burst is easy to miss
 *    ------------------------------------------------
 *    If firmware transmits only once and then stops, the analyzer may miss the
 *    event or catch it partially. Repeated transmission with visible delay
 *    makes validation much easier.
 *
 * 3. Sample rate matters
 *    ------------------------------------------------
 *    If analyzer sample rate is too low relative to SPI clock, decode quality
 *    becomes unreliable. Always use a comfortably high sample rate.
 *
 * 4. Hex view is better than ASCII view
 *    ------------------------------------------------
 *    For validation, prefer checking:
 *      0x48 0x65 0x6C 0x6C 0x6F 0x57 0x6F 0x72 0x6C 0x64
 *    rather than relying only on text decode.
 *
 * 5. MISO showing 0x00 is normal in this setup
 *    ------------------------------------------------
 *    Since no real slave is connected, received data is not meaningful.
 *    Analyzer may show transmitted MOSI byte along with 0x00 or dummy MISO data.
 *
 * ----------------------------------------------------------------------------
 * @main_loop_behavior
 * The main loop intentionally:
 *   - transmits "HelloWorld" multiple times,
 *   - leaves a visible delay between bursts,
 *   - performs floating-point calculations in the background.
 *
 * The floating-point section is not part of SPI communication itself.
 * It exists only to prove the CPU is alive and doing unrelated useful work
 * while SPI testing continues.
 *
 * ----------------------------------------------------------------------------
 * @about_fpu_debugcalc
 * FPU_DebugCalc() is a dummy floating-point workload that simulates sensor math:
 *   - ADC raw to voltage conversion
 *   - sensor scaling
 *   - simple filtering
 *
 * This is only for CPU/FPU observation and has no protocol role in SPI transfer.
 *
 * ----------------------------------------------------------------------------
 * @for_future_real_slave_integration
 * When converting this example from analyzer-only validation to real slave
 * communication, juniors must update the following carefully:
 *
 *   1. Add real slave chip-select handling
 *      - either hardware NSS if truly required and correctly understood,
 *      - or manual GPIO chip select (recommended for beginners).
 *
 *   2. Enable/configure MISO pin if response data is needed.
 *
 *   3. Confirm the slave's required:
 *      - SPI mode (0/1/2/3)
 *      - max clock frequency
 *      - setup/hold timing
 *      - bit order
 *      - transaction framing rules
 *      - command/response format
 *
 *   4. If slave expects transaction-level CS behavior, drive CS:
 *      - low before transfer,
 *      - high after transfer completes.
 *
 *   5. Ensure BSY clears before releasing CS or disabling SPI.
 *
 * ----------------------------------------------------------------------------
 * @driver_expectations
 * The SPI driver used here is assumed to:
 *   - wait for TXE before writing next frame
 *   - wait for BSY to clear before returning from blocking transmit
 *
 * That behavior is important because:
 *   - TXE only means data register can accept new data
 *   - BSY confirms the last bit has finished shifting out on the wire
 *
 * ----------------------------------------------------------------------------
 * @known_limitations_of_this_example
 * This is NOT yet a complete production SPI communication example.
 *
 * Missing or intentionally simplified items:
 *   - no real slave device
 *   - no response parsing
 *   - no timeout handling
 *   - no CRC/protocol framing
 *   - no interrupt/DMA-based SPI
 *   - no manual CS transaction control in current test version
 *   - no error recovery logic around OVR/MODF/etc.
 *
 * ----------------------------------------------------------------------------
 * @recommended_next_steps
 * For the next learning stage, extend this project in this order:
 *
 *   Step 1:
 *     Replace text payload with fixed hex patterns like:
 *       0x55, 0xAA, 0x0F, 0xF0
 *     to make bit-level verification easier.
 *
 *   Step 2:
 *     Add manual GPIO chip-select and observe cleaner framed transfers.
 *
 *   Step 3:
 *     Enable MISO and connect a real SPI slave.
 *
 *   Step 4:
 *     Build simple command/response transactions.
 *
 *   Step 5:
 *     Move from blocking SPI to interrupt or DMA if throughput requires it.
 *
 * ----------------------------------------------------------------------------
 * @summary
 * This file is a validated SPI2 master-transmit bring-up example.
 * It is mainly meant to teach and verify:
 *   - SPI pinmux
 *   - SPI peripheral init
 *   - blocking transmit
 *   - logic analyzer interpretation
 *   - common beginner pitfalls around framing and decode artifacts
 *
 * If this example appears to send "wrong ASCII" on analyzer, first suspect:
 *   1. analyzer framing,
 *   2. missing CS,
 *   3. capture settings,
 *   4. sample rate,
 * before suspecting the SPI hardware itself.
 ******************************************************************************/

#include <stdint.h>
#include "main.h"
#include <string.h>

void SystemInit(void)
{
#if (__FPU_PRESENT == 1U) && (__FPU_USED == 1U)
    SCB->CPACR |= ((3UL << (10U * 2U)) | (3UL << (11U * 2U)));
    __DSB();
    __ISB();
#endif
}

void delay_nop(uint32_t count)
{
    while (count--)
    {
        __asm volatile ("nop");
    }
}

/******************************************************************************
 * @brief      Handles unrecoverable application errors.
 *
 * @details    Disables interrupts and traps the CPU in an infinite loop,
 *             allowing the debugger to halt execution and inspect the system
 *             state at the point of failure.
 *
 * @return     None
 ******************************************************************************/
void Error_Handler(void)
{
    __disable_irq();

    while (1)
    {
        __NOP();
    }
}

volatile float dbg_adc_raw = 2048.0f;
volatile float dbg_vref = 3.3f;
volatile float dbg_adc_voltage = 0.0f;
volatile float dbg_sensor_offset = 1.65f;
volatile float dbg_sensor_sensitivity = 0.330f;
volatile float dbg_sensor_value = 0.0f;
volatile float dbg_filtered_value = 0.0f;
volatile uint32_t dbg_fpu_counter = 0;

SPI_Handle_t spi2_t;
GPIO_Handle_t spi_gpio_t;

static void FPU_DebugCalc(void);
void spi2_gpio_init(GPIO_Handle_t *spi_gpio_t);
void spi2_periph_init(SPI_Handle_t *spi2_t);

int main(void)
{
	char user_data[] = "HelloWorld";
    /*
        For SPI experiment: Using SPI2 in AFR5 mode for GPIOs
        PB12 -> SPI2_NSS
        PB13 -> SPI2_SCLK
        PB14 -> SPI2_MISO
        PB15 -> SPI2_MOSI
    */
    spi2_gpio_init(&spi_gpio_t);
    spi2_periph_init(&spi2_t);

    uint32_t tx_count = 0;

    /* Loop forever */
    while (1)
    {
        if (tx_count < 5)
        {
            spi_send_data(SPI2, (uint8_t *)user_data, strlen(user_data));
            tx_count++;

            // Gap between visible SPI bursts
            delay_nop(1000000);
        }
        else
        {
            // Deinit SPI Testing and observeing no clock/data activity on analyzer
            // spi_deinit(SPI2); // NOTE: As there is no CS line thus logic Analyser dosent know when to start & stop spi sampling!
        	delay_nop(1000000);

            // Reinitialize SPI and start again
            // spi2_periph_init(&spi2_t); // NOTE: As there is no CS line thus logic Analyser dosent know when to start & stop spi sampling!
            tx_count = 0;
        }

        // Background floating-point work every loop
        FPU_DebugCalc();
    }
}

static void FPU_DebugCalc(void)
{
    dbg_adc_voltage = (dbg_adc_raw * dbg_vref) / 4095.0f;
    dbg_sensor_value = (dbg_adc_voltage - dbg_sensor_offset) / dbg_sensor_sensitivity;
    dbg_filtered_value = (0.90f * dbg_filtered_value) + (0.10f * dbg_sensor_value);

    dbg_adc_raw += 17.0f;
    if (dbg_adc_raw > 4095.0f)
    {
        dbg_adc_raw = 0.0f;
    }

    dbg_fpu_counter++;
}

void spi2_gpio_init(GPIO_Handle_t *spi_gpio_t)
{
	spi_gpio_t->pGPIOx_addr = GPIOB;
	spi_gpio_t->pin_config.Mode = GPIO_MODE_ALTFN;
	spi_gpio_t->pin_config.Alternate = GPIO_AF5_SPI2;
	spi_gpio_t->pin_config.OPType = GPIO_OP_PP;
	spi_gpio_t->pin_config.Pull = GPIO_NOPULL;
	spi_gpio_t->pin_config.Speed = GPIO_SPEED_FREQ_HIGH;

	spi_gpio_t->pin_config.Pin = GPIO_PIN_13; // Config of SCLK-PB13
	gpio_init(spi_gpio_t);

	spi_gpio_t->pin_config.Pin = GPIO_PIN_15; // Config of MOSI-PB15
	gpio_init(spi_gpio_t);

    // Disabled due to no useage during testing!
//	spi_gpio_t->pin_config.Pin = GPIO_PIN_14; // Config of MISO-PB14
//	gpio_init(spi_gpio_t);

//	spi_gpio_t->pin_config.Pin = GPIO_PIN_12; // Config of NSS-PB12
//	gpio_init(spi_gpio_t);
}

void spi2_periph_init(SPI_Handle_t *spi2_t)
{
	spi2_t->Instance = SPI2;
	spi2_t->Init.Direction = SPI_COM_FD;
	spi2_t->Init.Mode = SPI_MODE_MASTER;
	spi2_t->Init.BaudRatePrescaler = SPI_CLK_DIV4; // 8MHz sclk
	spi2_t->Init.DataSize = BYTE_FRAME_LEN; // 8Bit mode
	spi2_t->Init.CLKPhase = SPI_CPHA_LOW;
	spi2_t->Init.CLKPolarity = SPI_CPOL_LOW;
	spi2_t->Init.NSS = SPI_SSM_ENABLED;

	spi_init(spi2_t); // This sets the settings while spi2 is disabled
	spi_ssi_state(spi2_t->Instance, ENABLE);
	spi_set_state(spi2_t->Instance, ENABLE);
}
