/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : PN532 NFC/RFID SPI command-response interface
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


/******************************************************************************
 * @project-03    STM32 <-> PN532 NFC/RFID SPI Command-Response Communication
 *
 * @purpose
 * This project demonstrates practical bidirectional SPI communication between:
 *
 *   - STM32F407VGT6 acting as SPI Master
 *   - PN532 NFC/RFID Module V3 acting as SPI peripheral
 *
 * Unlike the previous STM32-to-ESP32 transmit-only bring-up project, this
 * project implements complete command-response communication.
 *
 * The STM32:
 *
 *   1. Sends a command frame to the PN532 through MOSI
 *   2. Receives and validates the PN532 ACK frame
 *   3. Waits until the PN532 finishes processing the command
 *   4. Reads the resulting response frame through MISO
 *   5. Validates and processes the received response
 *
 * The primary goal is to build a reusable PN532 SPI driver that can later
 * perform NFC/RFID operations such as:
 *
 *   - Reading the PN532 firmware version
 *   - Configuring the PN532 SAM operating mode
 *   - Detecting ISO14443A cards and tags
 *   - Reading the UID of a detected NFC/RFID card
 *
 * ----------------------------------------------------------------------------
 * @current_scope
 * This firmware implements:
 *
 *   - STM32 configured as SPI Master using SPI2
 *   - PN532 Module V3 configured for SPI communication
 *   - Manual GPIO-based Chip Select control
 *   - PN532 command-frame transmission
 *   - PN532 ACK-frame reception and validation
 *   - PN532 status polling
 *   - PN532 response-frame reception
 *   - Frame length and checksum validation
 *   - Blocking SPI communication for initial bring-up
 *
 * Initial test command:
 *
 *   GetFirmwareVersion
 *
 * Expected result:
 *
 *   The PN532 returns its:
 *
 *   - IC identification
 *   - Firmware version
 *   - Supported NFC/RFID features
 *
 * ----------------------------------------------------------------------------
 * @hardware_mapping
 * STM32F407VGT6 (Master - SPI2):
 *
 *   PB12 -> PN532 SS/SSEL/CS
 *   PB13 -> PN532 SCK
 *   PB14 -> PN532 MISO
 *   PB15 -> PN532 MOSI
 *
 * Optional control signals:
 *
 *   STM32 GPIO -> PN532 IRQ   (optional; polling used initially)
 *   STM32 GPIO -> PN532 RSTO  (optional; depends on module implementation)
 *
 * Common connections:
 *
 *   STM32 GND  -> PN532 GND
 *   3.3 V      -> PN532 VCC, if supported by the selected module connection
 *
 * Important:
 *
 *   - A common ground is mandatory.
 *   - Verify the PN532 module voltage requirements before applying power.
 *   - STM32F407 and PN532 SPI logic signals must use compatible voltage levels.
 *   - Configure the switches/jumpers on the PN532 Module V3 for SPI mode.
 *   - Do not leave the module configured for I2C or HSU/UART mode.
 *
 * ----------------------------------------------------------------------------
 * @pn532_interface_selection
 * The PN532 supports multiple host interfaces:
 *
 *   - SPI
 *   - I2C
 *   - HSU/UART
 *
 * This project uses SPI.
 *
 * The interface-selection switches or jumpers on the PN532 Module V3 must be
 * placed in the SPI configuration before powering or resetting the module.
 *
 * The exact switch positions depend on the manufacturer and revision of the
 * PN532 Module V3. Verify the labels and documentation supplied with the
 * specific module before applying power.
 *
 * ----------------------------------------------------------------------------
 * @spi_configuration
 * STM32 SPI configuration:
 *
 *   - Peripheral      : SPI2
 *   - Mode            : Master
 *   - Direction       : Full duplex
 *   - Data Size       : 8-bit
 *   - Clock Polarity  : CPOL = 0
 *   - Clock Phase     : CPHA = 0
 *   - SPI Mode        : Mode 0
 *   - Bit Order       : LSB first
 *   - NSS Management  : Software
 *   - Chip Select     : Manual GPIO
 *
 * SPI clock:
 *
 *   The PN532 SPI clock must not exceed the limit specified in the PN532
 *   datasheet. For initial bring-up, use a conservative clock below 5 MHz.
 *
 *   The correct STM32 baud-rate prescaler must be calculated from the actual
 *   SPI2 peripheral clock.
 *
 * Example:
 *
 *   If SPI2 peripheral clock = 42 MHz:
 *
 *     DIV16 -> 2.625 MHz
 *
 *   This is suitable for initial communication testing.
 *
 * Important:
 *
 *   The PN532 SPI interface transfers each byte least-significant bit first.
 *   Configure STM32 SPI for LSB-first transmission or perform software bit
 *   reversal if the low-level SPI driver only supports MSB-first operation.
 *
 * ----------------------------------------------------------------------------
 * @pn532_spi_operations
 * PN532 SPI communication uses an operation byte before the PN532 frame.
 *
 * SPI operation bytes:
 *
 *   0x01 -> Data write
 *   0x02 -> Status read
 *   0x03 -> Data read
 *
 * Data write:
 *
 *   The STM32 sends:
 *
 *     1. PN532 SPI data-write operation
 *     2. Complete PN532 command frame
 *
 * Status read:
 *
 *   The STM32 polls the PN532 status until the module reports that response
 *   data is ready.
 *
 * Data read:
 *
 *   The STM32 sends the PN532 data-read operation and generates additional
 *   clock pulses to receive ACK or response bytes through MISO.
 *
 * ----------------------------------------------------------------------------
 * @pn532_frame_format
 * A normal PN532 command frame uses the following structure: refer to its 200 pages doc especially from Pg-No: 28 onwards! 
 *
 *   PREAMBLE | START CODE | LEN | LCS | TFI | COMMAND | DATA | DCS | POSTAMBLE
 *
 * Normal host-to-PN532 frame:
 *
 *   00 | 00 FF | LEN | LCS | D4 | COMMAND | DATA... | DCS | 00
 *
 * Field descriptions:
 *
 *   PREAMBLE   = 0x00
 *   START CODE = 0x00, 0xFF
 *   LEN        = Number of bytes from TFI through the final data byte
 *   LCS        = Length checksum
 *   TFI        = 0xD4 for a host-to-PN532 command
 *   COMMAND    = PN532 command identifier
 *   DATA       = Optional command parameters
 *   DCS        = Data checksum
 *   POSTAMBLE  = 0x00
 *
 * Checksum rules:
 *
 *   (LEN + LCS) & 0xFF = 0
 *
 *   (TFI + COMMAND + DATA bytes + DCS) & 0xFF = 0
 *
 * A normal PN532 response frame contains:
 *
 *   TFI              = 0xD5
 *   RESPONSE COMMAND = Original command value + 1
 *
 * Example:
 *
 *   Command:
 *     GetFirmwareVersion = 0x02
 *
 *   Expected response command:
 *     GetFirmwareVersion response = 0x03
 *
 * ----------------------------------------------------------------------------
 * @acknowledgement_frame
 * After accepting a valid command frame, the PN532 returns the following
 * six-byte ACK frame:
 *
 *   00 00 FF 00 FF 00
 *
 * The STM32 must verify the complete ACK frame before waiting for the actual
 * command response.
 *
 * Receiving an ACK means:
 *
 *   - The PN532 received the command frame
 *   - The command frame structure was accepted
 *
 * Receiving an ACK does not mean:
 *
 *   - The requested operation has finished
 *   - The final response is already available
 *   - The NFC/RFID operation succeeded
 *
 * The STM32 must wait for the PN532 to become ready and then read the separate
 * response frame.
 *
 * ----------------------------------------------------------------------------
 * @communication_sequence
 * Complete PN532 command-response transaction:
 *
 *   1. Build the PN532 command frame
 *   2. Calculate LEN and LCS
 *   3. Calculate DCS
 *   4. Drive CS LOW
 *   5. Send the SPI data-write operation
 *   6. Send the complete PN532 command frame
 *   7. Wait for SPI BSY to clear
 *   8. Drive CS HIGH
 *   9. Poll the PN532 status until ACK data is ready
 *  10. Drive CS LOW
 *  11. Send the SPI data-read operation
 *  12. Read and validate the six-byte ACK frame
 *  13. Drive CS HIGH
 *  14. Poll the PN532 status until command response data is ready
 *  15. Drive CS LOW
 *  16. Send the SPI data-read operation
 *  17. Read the PN532 response frame
 *  18. Wait for SPI BSY to clear
 *  19. Drive CS HIGH
 *  20. Validate response length, direction, command and checksums
 *  21. Process the returned response data
 *
 * Important:
 *
 *   SPI is controlled entirely by the STM32 master. The PN532 cannot generate
 *   the SPI clock by itself. Even when the PN532 has a response ready, the
 *   STM32 must generate clock pulses to receive the response through MISO.
 *
 * ----------------------------------------------------------------------------
 * @initial_test
 * The first command used for communication bring-up is:
 *
 *   GetFirmwareVersion
 *
 * Command code:
 *
 *   0x02
 *
 * Command payload:
 *
 *   No additional payload bytes
 *
 * Expected PN532 response data:
 *
 *   IC | VER | REV | SUPPORT
 *
 * Field descriptions:
 *
 *   IC      -> PN532 IC identification
 *   VER     -> Firmware version
 *   REV     -> Firmware revision
 *   SUPPORT -> Supported feature flags
 *
 * This command is recommended for initial testing because it:
 *
 *   - Does not require an NFC card
 *   - Does not require antenna-field configuration
 *   - Produces a small and predictable response
 *   - Confirms that both MOSI and MISO are working
 *   - Confirms command, ACK and response handling
 *
 * ----------------------------------------------------------------------------
 * @planned_nfc_sequence
 * After GetFirmwareVersion succeeds, the intended NFC/RFID sequence is:
 *
 *   Step 1:
 *     Send SAMConfiguration to configure normal PN532 operation.
 *
 *   Step 2:
 *     Send InListPassiveTarget for ISO14443A card detection.
 *
 *   Step 3:
 *     Wait for a card or NFC tag to enter the RF field.
 *
 *   Step 4:
 *     Receive and validate the PN532 response.
 *
 *   Step 5:
 *     Extract and print the detected card UID.
 *
 * ----------------------------------------------------------------------------
 * @driver_behavior_expectations
 * The low-level STM32 SPI driver is expected to:
 *
 *   - Wait for TXE before writing each byte
 *   - Wait for RXNE before reading each received byte
 *   - Use 8-bit data-register access
 *   - Clear any overrun condition correctly
 *   - Wait for BSY to clear before releasing CS
 *   - Generate dummy bytes when receiving PN532 data
 *   - Support full-duplex transmit and receive operations
 *
 * Important status flags:
 *
 *   TXE  = Transmit data register empty
 *   RXNE = Receive data register contains unread data
 *   BSY  = SPI peripheral is actively transferring data
 *   OVR  = Receive data was not read before the next byte arrived
 *
 * During every SPI byte transmitted by the STM32, another byte is received.
 * Therefore, the receive data register must be handled even when the received
 * byte is not needed.
 *
 * ----------------------------------------------------------------------------
 * @why_manual_cs_is_used
 * Manual GPIO-based Chip Select is used because it:
 *
 *   - Provides explicit control over each PN532 SPI operation
 *   - Keeps command, status and data-read operations separately framed
 *   - Allows BSY to be checked before releasing the PN532
 *   - Simplifies debugging with a logic analyzer
 *   - Avoids hardware-NSS timing differences
 *   - Makes the low-level driver easier to understand during bring-up
 *
 * CS must remain LOW for the complete SPI operation and must only return HIGH
 * after the final transmitted byte has physically left the STM32 SPI hardware.
 *
 * ----------------------------------------------------------------------------
 * @polling_and_irq
 * Initial implementation:
 *
 *   - PN532 readiness is checked using SPI status polling
 *   - The optional PN532 IRQ pin is not required
 *
 * Future implementation:
 *
 *   - Connect the PN532 IRQ output to an STM32 external-interrupt GPIO
 *   - Allow the PN532 to notify the STM32 when ACK or response data is ready
 *   - Remove repeated status polling
 *   - Reduce unnecessary CPU usage
 *
 * ----------------------------------------------------------------------------
 * @timeout_requirements
 * Every wait operation must eventually use a timeout.
 *
 * Timeouts are required while waiting for:
 *
 *   - SPI TXE
 *   - SPI RXNE
 *   - SPI BSY to clear
 *   - PN532 ACK readiness
 *   - PN532 command-response readiness
 *
 * A timeout prevents the firmware from becoming permanently blocked when:
 *
 *   - The PN532 is disconnected
 *   - The module is configured for the wrong interface
 *   - CS or SPI wiring is incorrect
 *   - The PN532 does not respond
 *   - A card operation fails or takes too long
 *
 * ----------------------------------------------------------------------------
 * @debugging_notes
 * If no valid PN532 response is received, check in this order:
 *
 *   1. PN532 module is configured for SPI mode
 *   2. PN532 and STM32 share a common ground
 *   3. Module supply voltage and logic levels are correct
 *   4. CS, SCK, MOSI and MISO wiring is correct
 *   5. SPI uses Mode 0
 *   6. SPI uses LSB-first bit order
 *   7. SPI clock does not exceed the PN532 limit
 *   8. Correct SPI operation byte is transmitted
 *   9. Command-frame LEN and LCS are correct
 *  10. Command-frame DCS is correct
 *  11. ACK frame is read before the response frame
 *  12. STM32 waits until the PN532 reports ready
 *  13. Dummy bytes are transmitted while reading MISO
 *  14. CS stays LOW for the complete operation
 *  15. BSY clears before CS returns HIGH
 *
 * A logic analyzer should show:
 *
 *   - CS transitioning LOW before each SPI operation
 *   - Clock pulses only while CS is LOW
 *   - Command data on MOSI
 *   - ACK and response data on MISO
 *   - CS returning HIGH after the transfer completes
 *
 * ----------------------------------------------------------------------------
 * @known_limitations
 * Initial implementation limitations:
 *
 *   - Blocking/polling-based SPI communication
 *   - No SPI DMA
 *   - PN532 IRQ pin not used
 *   - No FreeRTOS integration
 *   - No automatic retry mechanism
 *   - Only normal PN532 information frames supported initially
 *   - NFC card read/write operations not yet implemented
 *   - No application-level recovery after PN532 communication failure
 *
 * ----------------------------------------------------------------------------
 * @recommended_next_steps
 * Step 1:
 *   Configure the PN532 Module V3 for SPI mode.
 *
 * Step 2:
 *   Verify basic SPI wiring and conservative clock configuration.
 *
 * Step 3:
 *   Implement PN532 status-read, data-write and data-read operations.
 *
 * Step 4:
 *   Send GetFirmwareVersion and validate its ACK and response.
 *
 * Step 5:
 *   Send SAMConfiguration.
 *
 * Step 6:
 *   Detect an ISO14443A card using InListPassiveTarget.
 *
 * Step 7:
 *   Extract and print the detected card UID.
 *
 * Step 8:
 *   Add communication timeouts and structured error codes.
 *
 * Step 9:
 *   Replace status polling with the PN532 IRQ signal.
 *
 * Step 10:
 *   Add interrupt-based or DMA-based SPI transfers if required.
 *
 * ----------------------------------------------------------------------------
 * @summary
 * This project demonstrates:
 *
 *   - Bidirectional STM32-to-PN532 SPI communication
 *   - PN532 command-frame construction
 *   - ACK-frame reception and validation
 *   - PN532 readiness polling
 *   - Response-frame reception and validation
 *   - Full MOSI and MISO communication
 *   - Foundation for NFC/RFID card detection and UID reading
 *
 * Communication direction:
 *
 *   STM32 MOSI -> PN532 command
 *   PN532 MISO -> STM32 ACK and response
 *
 * If communication fails, verify:
 *
 *   1. Interface-selection switches
 *   2. Power and common ground
 *   3. SPI wiring
 *   4. SPI Mode 0
 *   5. LSB-first transfer
 *   6. SPI clock frequency
 *   7. PN532 operation bytes
 *   8. ACK handling
 *   9. Frame lengths and checksums
 *  10. Readiness polling and timeouts
 *
 ******************************************************************************/
#include <stdint.h>
#include "main.h"
#include <string.h>

/******************************************************************************
 * PN532 SPI protocol definitions
 ******************************************************************************/
#define PN532_SPI_DATA_WRITE          0x01U // STM32 writes a PN532 command frame
#define PN532_SPI_STATUS_READ         0x02U // STM32 reads PN532 ready/busy status
#define PN532_SPI_DATA_READ           0x03U // STM32 clocks out ACK/response data from PN532

#define PN532_PREAMBLE                0x00U // First byte of every normal PN532 frame
#define PN532_START_CODE_1            0x00U // First byte of PN532 frame start sequence: 00 FF
#define PN532_START_CODE_2            0xFFU // Second byte of PN532 frame start sequence: 00 FF
#define PN532_POSTAMBLE               0x00U // Final byte appended after the frame checksum

#define PN532_HOST_TO_PN532           0xD4U // TFI value used for commands sent from STM32/host to PN532
#define PN532_PN532_TO_HOST           0xD5U // TFI value used for responses sent from PN532 back to STM32/host

#define PN532_CMD_GET_FIRMWARE        0x02U // GetFirmwareVersion: reads PN532 IC, firmware version, revision and feature support
#define PN532_CMD_SAM_CONFIGURATION   0x14U // SAMConfiguration: configures PN532 operating mode before NFC operations
#define PN532_CMD_IN_LIST_PASSIVE     0x4AU // InListPassiveTarget: searches for nearby passive NFC/RFID tags

#define PN532_READY_BIT               0x01U // Bit 0 of PN532 SPI status byte: 1 = ACK/response data is ready to read

#define PN532_MAX_FRAME_SIZE          64U // Maximum PN532 frame buffer used by this driver during initial bring-up
#define PN532_MAX_UID_SIZE            10U //Type-A UID can be 4, 7, or 10 bytes, so 10 is a sensible buffer

// Various statuses from documnetation!
typedef enum{
    PN532_OK = 0,
    PN532_NO_TAG,
    PN532_ERR_TIMEOUT,
    PN532_ERR_ACK,
    PN532_ERR_FRAME,
    PN532_ERR_CHECKSUM,
    PN532_ERR_RESPONSE,
    PN532_ERR_BUFFER
} pn532_status_t;

/*
 * Debug variables: These are deliberately global/volatile so they can be watched directly from the STM32CubeIDE debugger.
 */
volatile pn532_status_t dbg_pn532_status = PN532_OK;
volatile uint8_t dbg_fw_ic = 0;
volatile uint8_t dbg_fw_version = 0;
volatile uint8_t dbg_fw_revision = 0;
volatile uint8_t dbg_fw_support = 0;
volatile uint8_t dbg_uid[PN532_MAX_UID_SIZE] = {0};
volatile uint8_t dbg_uid_length = 0;

void SystemInit(void)
{
#if (__FPU_PRESENT == 1U) && (__FPU_USED == 1U)
    SCB->CPACR |= ((3UL << (10U * 2U)) | (3UL << (11U * 2U)));
    __DSB();
    __ISB();
#endif
}

void delay_nop(uint32_t count)
{
    while (count--)
    {
        __asm volatile ("nop");
    }
}

/******************************************************************************
 * @brief      Handles unrecoverable application errors.
 *
 * @details    Disables interrupts and traps the CPU in an infinite loop,
 *             allowing the debugger to halt execution and inspect the system
 *             state at the point of failure.
 *
 * @return     None
 ******************************************************************************/
void Error_Handler(void)
{
    __disable_irq();

    while (1)
    {
        __NOP();
    }
}

volatile float dbg_adc_raw = 2048.0f;
volatile float dbg_vref = 3.3f;
volatile float dbg_adc_voltage = 0.0f;
volatile float dbg_sensor_offset = 1.65f;
volatile float dbg_sensor_sensitivity = 0.330f;
volatile float dbg_sensor_value = 0.0f;
volatile float dbg_filtered_value = 0.0f;
volatile uint32_t dbg_fpu_counter = 0;

SPI_Handle_t spi2_t;
GPIO_Handle_t spi_gpio_t;

static void FPU_DebugCalc(void);
void spi2_gpio_init(GPIO_Handle_t *spi_gpio_t);
void spi2_periph_init(SPI_Handle_t *spi2_t);

void pn532_com_select(void);
void pn532_com_deselect(SPI_RegDef_t *pSPIx_addr);
uint8_t pn532_read_status(void);
pn532_status_t pn532_wait_ready(uint32_t max_polls);
pn532_status_t pn532_write_command(uint8_t command, const uint8_t *data, uint8_t data_len);
pn532_status_t pn532_read_ack(void);
pn532_status_t pn532_read_response(uint8_t expected_command, uint8_t *response, uint8_t response_size, uint8_t *response_len);
uint8_t pn532_spi_transfer_byte(uint8_t byte);
pn532_status_t pn532_command_transaction(uint8_t command, const uint8_t *command_data, uint8_t command_data_len, uint8_t *response, uint8_t response_size, uint8_t *response_len,  uint32_t response_poll_limit);

int main(void)
{
    spi2_gpio_init(&spi_gpio_t);
    spi2_periph_init(&spi2_t);

    while (1)
    {

    }
}

static void FPU_DebugCalc(void)
{
    dbg_adc_voltage = (dbg_adc_raw * dbg_vref) / 4095.0f;
    dbg_sensor_value = (dbg_adc_voltage - dbg_sensor_offset) / dbg_sensor_sensitivity;
    dbg_filtered_value = (0.90f * dbg_filtered_value) + (0.10f * dbg_sensor_value);

    dbg_adc_raw += 17.0f;
    if (dbg_adc_raw > 4095.0f)
    {
        dbg_adc_raw = 0.0f;
    }

    dbg_fpu_counter++;
}

void spi2_gpio_init(GPIO_Handle_t *spi_gpio_t)
{
	spi_gpio_t->pGPIOx_addr = GPIOB;
	spi_gpio_t->pin_config.Mode = GPIO_MODE_ALTFN;
	spi_gpio_t->pin_config.Alternate = GPIO_AF5_SPI2;
	spi_gpio_t->pin_config.OPType = GPIO_OP_PP;
	spi_gpio_t->pin_config.Pull = GPIO_NOPULL;
	spi_gpio_t->pin_config.Speed = GPIO_SPEED_FREQ_HIGH;

	spi_gpio_t->pin_config.Pin = GPIO_PIN_13; // Config of SCLK-PB13
	gpio_init(spi_gpio_t);

	spi_gpio_t->pin_config.Pin = GPIO_PIN_15; // Config of MOSI-PB15
	gpio_init(spi_gpio_t);

	spi_gpio_t->pin_config.Pin = GPIO_PIN_14; // Config of MISO-PB14
	gpio_init(spi_gpio_t);

	// PB12 as manual CS GPIO, not AF
	spi_gpio_t->pin_config.Mode = GPIO_MODE_OUTPUT;
	spi_gpio_t->pin_config.Alternate = 0;
	spi_gpio_t->pin_config.Pin = GPIO_PIN_12; // Config of NSS-PB12
	gpio_init(spi_gpio_t);

    gpio_set_pin_level(GPIOB, GPIO_PIN_12, 1); // CS idle high
}

void spi2_periph_init(SPI_Handle_t *spi2_t)
{
	spi2_t->Instance = SPI2;
	spi2_t->Init.Direction = SPI_COM_FD;
	spi2_t->Init.Mode = SPI_MODE_MASTER;
	spi2_t->Init.BaudRatePrescaler = SPI_CLK_DIV4; // 4MHz sclk as pn532 is rated for max 5MHz
	spi2_t->Init.DataSize = BYTE_FRAME_LEN; // 8Bit mode
	spi2_t->Init.CLKPhase = SPI_CPHA_LOW;
	spi2_t->Init.CLKPolarity = SPI_CPOL_LOW;
	spi2_t->Init.NSS = SPI_SSM_ENABLED;

	spi_init(spi2_t); // This sets the settings while spi2 is disabled

    /* PN532 SPI transfers every byte LSB-first. */
    SPI2->CR1 |= SPI_CR1_LSBFIRST;

	spi_ssi_state(spi2_t->Instance, ENABLE);
    spi_set_state(spi2_t->Instance, ENABLE);
}

void pn532_com_select(void)
{
    gpio_set_pin_level(GPIOB, GPIO_PIN_12, 0); // Pull CS pin low to begin communication
}

void pn532_com_deselect(SPI_RegDef_t *pSPIx_addr)
{
    while (pSPIx_addr->SR & (1U << SPI_SR_BSY)); // Wait until SPI is not busy!

    gpio_set_pin_level(GPIOB, GPIO_PIN_12, 1); // Pull CS pin high to end communication
}

/******************************************************************************
 * @brief  Read the PN532 SPI status byte.
 *
 * @return Raw PN532 status byte.
 *
 * Bit 0:
 *      0 = PN532 has no frame ready
 *      1 = PN532 has a frame ready
 ******************************************************************************/
uint8_t pn532_read_status(void)
{
    uint8_t status;

    pn532_com_select(); // Initiate com over spi
    
    // First tell PN532 that this SPI transaction is a STATUS READ & byte simultaneously received here is ignored.
    (void)pn532_spi_transfer_byte(PN532_SPI_STATUS_READ);

    // Send dummy byte purely to generate clocks so PN532 can return status.
    status =  spi_transfer_data(SPI2, 0xFF);

    pn532_com_deselect(SPI2);
    
    return status;
}

/******************************************************************************
 * @brief  Poll PN532 until a response/ACK frame becomes available.
 *
 * @param  max_polls Maximum number of polling attempts.
 *
 * @return PN532_OK if ready, otherwise PN532_ERR_TIMEOUT.
 *
 * @note
 * This is deliberately simple for bring-up.
 * Later replace delay_nop() with a proper millisecond timer/SysTick timeout.
 ******************************************************************************/
pn532_status_t pn532_wait_ready(uint32_t max_polls)
{
    while (max_polls--)
    {
        if ((pn532_read_status() & PN532_READY_BIT) != 0)
        {
            // read status function returned 0000 0001, thus 0001 & 0001 -> 1/true
            return PN532_OK;
        }
        delay_nop(10000);
    }

    return PN532_ERR_TIMEOUT; // In case of failure to receive any response from module
}

/******************************************************************************
 * @brief  Build and transmit one PN532 normal command frame.
 *
 * Frame generated:
 *
 *   00 00 FF LEN LCS D4 COMMAND DATA... DCS 00
 *
 * SPI wire transaction:
 *
 *   01 00 00 FF LEN LCS D4 COMMAND DATA... DCS 00
 *   ^^
 *   PN532 SPI DATA_WRITE operation
 *
 * @param command    PN532 command byte.
 * @param data       Optional command parameter bytes.
 * @param data_len   Number of parameter bytes.
 ******************************************************************************/
pn532_status_t pn532_write_command(uint8_t command, const uint8_t *data, uint8_t data_len)
{
    uint8_t frame[PN532_MAX_FRAME_SIZE]; // Complete frame to be sent to module
    uint8_t len = (uint8_t)(2U + data_len); // TFI = 1 byte, COMMAND = 1 byte, DATA = data_len bytes
    uint8_t frame_size = (uint8_t)(len + 7U); // PREAMBLE{1B}, START CODE{2B}, LEN + LCS{2B}, data field{lenB}, DCS{1B}, POSTAMBLE{1B} thus Total = (len + 7) B or Bytes 

    if (frame_size > PN532_MAX_FRAME_SIZE)
    {
        return PN532_ERR_BUFFER; // Invalid as it exceeds com protocol of this NXP module
    }

    // Building frame with relevant static & dynamic data
    frame[0] = PN532_PREAMBLE;
    frame[1] = PN532_START_CODE_1;
    frame[2] = PN532_START_CODE_2;
    frame[3] = len;
    frame[4] = (uint8_t)(0U - len); // LEN + LCS must equal 0 modulo 256.
    frame[5] = PN532_HOST_TO_PN532;
    frame[6] = command;
    // Inserting DATA along with checksum
    uint8_t checksum = PN532_HOST_TO_PN532;
    checksum += command;
    for (uint8_t i = 0; i < data_len; i++)
    {
        // From 8th onwards data needs to be inserted & add the data into checksum!
        frame[7U + i] = data[i];
        checksum += data[i];
    }
    // TFI + COMMAND + DATA + DCS must equal 0 modulo 256.
    frame[7U + data_len] = (uint8_t)(0U - checksum);
    frame[8U + data_len] = PN532_POSTAMBLE;

    // Sending write command over SPI line
    pn532_com_select();
    (void)pn532_spi_transfer_byte(PN532_SPI_DATA_WRITE); // PN532 SPI DATA_WRITE operation
    for (uint8_t i = 0; i < frame_size; i++)
    {
        (void)pn532_spi_transfer_byte(frame[i]);
    }

    pn532_deselect();
    return PN532_OK;
}

/******************************************************************************
 * @brief  Read and validate the six-byte PN532 ACK frame.
 ******************************************************************************/
pn532_status_t pn532_read_ack(void)
{
    static const uint8_t expected_ack[6] = { 0x00, 0x00, 0xFF, 0x00, 0xFF, 0x00 }; // The known good response from PN532-module

    uint8_t ack[6];
    pn532_select();
    
    // DATA_READ tells PN532 that subsequent clocks are for reading a frame.
    (void)pn532_spi_transfer_byte(PN532_SPI_DATA_READ);
    for (uint8_t i = 0; i < sizeof(ack); i++)
    {
        // Accept the acknowledgement's from module!
        ack[i] = pn532_spi_transfer_byte(0x00);
    }

    pn532_deselect();

    if (memcmp(ack, expected_ack, sizeof(expected_ack)) != 0) // If response from module dosent match the known "expected_ack"
    {
        return PN532_ERR_ACK;
    }

    return PN532_OK;
}

/******************************************************************************
 * @brief  Read and validate a PN532 normal response frame.
 *
 * @param expected_command Original command sent to PN532.
 * @param response         Destination for command-specific response data.
 * @param response_size    Capacity of response[].
 * @param response_len     Number of command-specific bytes returned.
 *
 * Example:
 *
 * Command-01: 0x14 SAMConfiguration
 *  Expected response command:  0x15
 *
 * Command-02: 0x4A InListPassiveTarget
 *  Expected response command:  0x4B
 ******************************************************************************/
pn532_status_t pn532_read_response(uint8_t expected_command, uint8_t *response, uint8_t response_size, uint8_t *response_len)
{
    uint8_t frame[PN532_MAX_FRAME_SIZE];

    pn532_com_select();
    (void)pn532_spi_transfer_byte(PN532_SPI_DATA_READ);
    // First receive the first 5 bytes
    for (uint8_t i = 0; i < 5U; i++)
    {
        frame[i] = pn532_spi_transfer_byte(0x00);
    }

    if(frame[0] == 0x00U && frame[1] == 0x00U && frame[2] == 0xFFU)
    {
        pn532_deselect();
        return PN532_ERR_FRAME;
    }

    uint8_t len = frame[3];
    uint8_t lcs = frame[4];

    if((uint8_t)(len+lcs) != 0)
    {
        pn532_deselect();
        return PN532_ERR_CHECKSUM;
    }

    uint16_t total_frame_size = (uint16_t)len + 7U;

    if (total_frame_size > PN532_MAX_FRAME_SIZE)
    {
        pn532_deselect();
        return PN532_ERR_BUFFER;
    }

    // After these checks its safe to receive rest of the frame sent over MISO by pn532: TFI + RESPONSE_COMMAND + DATA... + DCS + POSTAMBLE
    for (uint16_t i = 5U; i < total_frame_size; i++)
    {
        frame[i] = pn532_spi_transfer_byte(0x00);
    }
    pn532_deselect();

    // Special PN532 application error frame contains 0x7F.
    if ((len == 1U) && (frame[5] == 0x7FU))
    {
        return PN532_ERR_RESPONSE;
    }
    if (len < 2U)
    {
        return PN532_ERR_FRAME;
    }

    // Verify packet-data checksum.
    uint8_t checksum = 0;
    for (uint8_t i = 0; i < len; i++)
    {
        checksum += frame[5U + i];
    }

    /* DCS follows the LEN bytes. */
    checksum += frame[5U + len];
    if (checksum != 0U)
    {
        return PN532_ERR_CHECKSUM;
    }

    /* Verify postamble. */
    if (frame[6U + len] != PN532_POSTAMBLE)
    {
        return PN532_ERR_FRAME;
    }

    // PN532 -> Host response TFI must be D5.
    if (frame[5] != PN532_PN532_TO_HOST)
    {
        return PN532_ERR_RESPONSE;
    }

    // Response command is always original command + 1.
    if (frame[6] != (uint8_t)(expected_command + 1U))
    {
        return PN532_ERR_RESPONSE;
    }

    // Remove TFI and response-command bytes & remaining is command-specific response data.
    uint8_t payload_len = (uint8_t)(len - 2U);
    if (payload_len > response_size)
    {
        return PN532_ERR_BUFFER;
    }

    if ((response != NULL) && (payload_len > 0U))
    {
        memcpy(response, &frame[7], payload_len);
    }

    *response_len = payload_len;
    return PN532_OK;
}

uint8_t pn532_spi_transfer_byte(uint8_t byte)
{
    return spi_transfer_data(SPI2, byte);
}

/******************************************************************************
 * @brief Execute one complete PN532 command-response transaction.
 *
 * Sequence: Write command -> Wait READY -> Read ACK -> Wait READY -> Read response
 ******************************************************************************/
pn532_status_t pn532_command_transaction(uint8_t command, const uint8_t *command_data, uint8_t command_data_len, uint8_t *response, uint8_t response_size, uint8_t *response_len,  uint32_t response_poll_limit)
{
    pn532_status_t status;

    status = pn532_write_command(command, command_data, command_data_len);
    if (status != PN532_OK)
    {
        return status;
    }

    // PN532 should produce ACK within this amount of retries!
    status = pn532_wait_ready(200U);
    if (status != PN532_OK)
    {
        return status;
    }

    status = pn532_read_ack();
    if (status != PN532_OK)
    {
        return status;
    }

    // Command execution can take considerably longer than generation of ACK.
    status = pn532_wait_ready(response_poll_limit);
    if (status != PN532_OK)
    {
        return status;
    }

    return pn532_read_response(command, response, response_size, response_len);
}